# Generated by Django 3.0.2 on 2020-01-15 15:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa Produktu')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Odnośnik')),
                ('icon', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Ikona Produktu')),
                ('price', models.IntegerField(verbose_name='Cena')),
                ('promotion', models.BooleanField(default=False)),
                ('shop', models.ManyToManyField(to='products.Shop', verbose_name='Shop')),
            ],
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
