# Generated by Django 3.0.2 on 2020-01-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200117_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='icon',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Ikona sklepu'),
        ),
    ]
